### ISSUE TITLE
Búsqueda de perfiles

### ISSUE THREAD

**Issue by eliocamp** [INTA-Suelos/SISINTAR#10]
Posiblidades: 

1. Usar la búsqueda de sisinta que está acá: http://sisinta.inta.gob.ar/es/busquedas/nueva
    **Ventajas**:    
          * Se puede buscar por cualquer variable 
          * Se pueden hacer búsquedas complejas
     **Desventajas**: 
          * Es leeeento. 
          * Hay que entender cómo construir la URL correctamente

1. Descargar el geojson en http://sisinta.inta.gob.ar/es/perfiles.geojson
    **Ventajas**: 
          * Trivial de implementar
          * Rápido (en principio)
     **Desventajas**: 
          * Descargar el archivo parece ser muy lento o no confiable. 
          * Hay que descargarlo una vez y actualizarlo sólo cada tanto (¿bajo qué criterio se actualiza?)
          * Riesgo de tener datos desactualizados.
          * Sólo permite buscar por lon lat, fecha y/o clase
 
1. Meter los datos de perfiles.geojson en el paquete
    **Ventajas**: 
          * Trivial de implementar
          * Rápido
     **Desventajas**: 
          * Riesgo de tener datos desactualizados.
          * Sólo permite buscar por lon lat, fecha y/o clase
 
1. Descargar toda la base de datos localmente. 
      **Ventajas**: 
          * Trivial de implementar
          * Rápido (una vez descargado)
          * Permite filtrar por cualquier variable
     **Desventajas**: 
          * Muy lento la primera vez.
          * Ocupa mucho espacio. 
          * Hay que descargarlo una vez y actualizarlo sólo cada tanto (¿bajo qué criterio se actualiza?)
          * Riesgo de tener datos desactualizados.

Lo ideal sería la primera.

**Comment by angelini75** [comment]
Hola @eliocamp 

La actualización se produce cada vez que se cargan nuevos datos a sisinta, o que se corrigen datos erroneos, o que se agregan datos a perfiles ya existentes. En general una actualización semanal sería más que suficiente. Le solicité al desarrollador si puede colgar un csv de toda la base en un link de donde nosotros podamos tomar la base. Esto permitiría hacer busqueda sobre todas las propiedades, lo cual es más importante que el riesgo de tener datos no actualizados.

Hasta que no tengamos el csv, yo diría de descargar localmente? toda la base una vez por mes

**Comment by eliocamp** [comment]
Estoy probando descargando todos los csv de la base de datos y es un proceso muy lento (tarda más de una hora). 

Ahora que lo pienso, "buscar" en toda la base de datos no tiene mucho sentido porque implicaría leerla toda en memoria y luego filtrar. La idea de la búsqueda es justamente levantar solo los datos necesarios. 

Creo que tiene más sentido buscar en base a las variables de sitio y serie.

**Comment by dariorodriguez** [comment]
Hola Elio. El desarrollador de Sisinta tiene en carpeta la mejora de la opción 1. Pasa que como siempre le vamos agrgando cosas eso todavía no lo hizo. Pero lo puede hacer
