### ISSUE TITLE
imputar_profundidad_inferior()

### ISSUE THREAD

**Issue by eliocamp** [INTA-Suelos/SISINTAR#13]
Cosas que hay que validar y/o corregir en los perfiles para tener una validación mínima. 

* [x] Valores faltantes en profundidad (#8)

**Comment by dariorodriguez** [comment]
Esto lo venimos corrigiendo pero al mismo tiempo avanza la carga y aparecen nuevos errores. Lo único que se me ocurre es que si EN EL ULTIMO HORIZONTE o CAPA no aparece la profundidad inferior, se le asigne el valor de la profundidad superior del horizonte + 10 cm.

**Comment by angelini75** [comment]
@dariorodriguez fijate que la app te da la opción de agregarle los cm que quieras. Por default pone 5 en Grosor del último horizonte (cm), lo cual me parece bien.
