### ISSUE TITLE
get_variable_*()

### ISSUE THREAD

**Issue by paocorrales** [INTA-Suelos/SISINTAR#14]
En la lista de funciones a implementar tenemos esto:

a) Obtener nombre de variales
      i)  get_variable_sitio()
      ii) get_variable_horizonte()

No recordamos a que referían. ¿Nos lo podrían recordar?

**Comment by angelini75** [comment]
No recuerdo bien, pero podría ser que se rerfiera a lo mismo que la función #15 o bien que devuelva el nombre la las variables de los data frames resultantes de #15

**Comment by paocorrales** [comment]
Seguimos entonces en #15
