### ISSUE TITLE
Documentar variables

### ISSUE THREAD

**Issue by eliocamp** [INTA-Suelos/SISINTAR#16]
Agregar esta información en la documentación:
https://docs.google.com/spreadsheets/d/1cLS1jBjXUzfWOH-I7LbzSDJJiQuv9usOaDUdpBuyZBc/edit?usp=sharing

Además, agregar funciones que tomen el nombre de la columna y devuelva el nombre humano (para plotear y esas cosas)

**Comment by paocorrales** [comment]
@angelini75 nos gustaría resolver el tema del nombre de las columnas, sabés para cuando podrían tener completo el archivo que menciona Elio arriba?

**Comment by angelini75** [comment]
Hecho, ya completé la tabla hasta la cuarta columna.
