### ISSUE TITLE
Devolver información sintetizada

### ISSUE THREAD

**Issue by paocorrales** [INTA-Suelos/SISINTAR#17]
Generar horizontes estandarizados a partir de horizontes originales. .Por ejemplo, generar una tabla que contenga Latitud, * Longitud, Materia_Oránica_0-30cm (limite superior = 0, limite inferior = 30).

Utilizar diferentes métodos de sintetizado: función spline o promedio ponderado, o valor para una profundidad única (ej. 5 cm)

**Comment by eliocamp** [comment]
¿Qué hay que hacer si un perfil no tiene datos en los horizontes pedidos? Por ejemplo, pido promedio ponderado en horizontes c(0, 30, 60, 90, 120, 150) pero el perfil tiene profundidad hasta 140. ¿El horizonte 120 a 150 debería devolver NA?

**Comment by eliocamp** [comment]
@angelini75 ¿Tenés alguna documentación para pasarnos sobre el método de splines para que lo agreguemos?

**Comment by angelini75** [comment]
Sobre que hacer si no hay datos para la profundidad solicitada, es devolver el resultado usando los datos que caen dentro del rango, o sea, 120-140.

**Comment by angelini75** [comment]
Sobre spline
Spline es una función del paquete ithir que no está en cran
http://smartdigiag.com/DSM_book/pages/ithir/

Este tipo es el que la implementó y tiene un repo sólo  con la función, así que se puede usar esta citando el autor
https://github.com/brendo1001/EA_splines_soil

**Comment by eliocamp** [comment]
> Sobre que hacer si no hay datos para la profundidad solicitada, es devolver el resultado usando los datos que caen dentro del rango, o sea, 120-140.

El problema de eso es que el resultado de la operación es imprediscible. Uno le pide estandarizar los perfiles en una serie de profundidades y luego no hay forma de predecir qué profundidades salen al final. ¿No jode eso?

**Comment by angelini75** [comment]
Lo que suele pasar es que a veces hay falta de datos en el medio del horizonte, o el muestreo sólo tomó el centro del horizonte y no el total. Por esta razón, y porque generalmente hay escasez de datos, es preferible que devuelva un promedio ponderado de los pocos datos que hay a que elimine datos. En el ejemplo que vos das se puede subsanar el problema tomando la profundidad total del perfil, en este caso 140 cm, e introducirlo como dato adicional si es necesario, pero no para el cálculo del promedio ponderado. Quizás lo más sano sería habilitar la opción que devuelva NA como un argumento TRUE/FALSE.

Yo lo había implementado así. Pueden corroborar si no tiene fallas u optimizarla

```
weighted.av <- 
  function(sp, depths, data){
    #sp = c("ph", "cec", "oc", "clay", "silt", "sand", "cf")
    depth = data.frame(ul = depths[1:length(depths)-1], 
                       ll = depths[2:length(depths)])
    depth = cbind(interval=paste0(depth$ul,"_",depth$ll),depth)
    a = tidyr::crossing(sp, depth$interval)
    a = paste0(a$sp,'_', a$`depth$interval`)
    
    dt <- vector("list", length(a))
    library(tidyverse)
    for (i in sp) {
      for (j in depth$interval) {
        index <- which(a %in% paste0(i, '_', j))
        d <- depth[which(depth$interval %in% j),2:3]
        x <- data %>% 
          select(id_prof,ul,ll,i) %>% 
          filter(ul < d$ll & ll >= d$ul) %>% 
          arrange(!desc(id_prof)) %>% 
          dplyr::group_by(id_prof) %>% 
          mutate(ll = if_else(ll>d$ll,true=d$ll,false=ll),
                 ul = if_else(ul<=d$ul,true=d$ul,false=ul),
                 thickness = ll - ul,
                 w = (ll-ul)/sum(thickness),
                 w_ = eval(parse(text = i)) * w,
                 isum = sum(w_, na.rm=TRUE),
                 isnan = as.numeric(is.nan(w)),
                 isna = sum(!is.na(eval(parse(text = i)))),
                 value = if_else(isnan == 1,
                                 99999,
                                 if_else(isna > 0,
                                        isum,
                                        99999)))
        x$value[x$value==99999] <- NA
        x <- group_by(x, id_prof) 
        x <- summarise(x, x = unique(value))
        names(x)[2] <- paste0(i,'_',j)
        dt[[index]] <- x
        names(dt)[index] <- paste0(i,'_',j)
      }
    }
    
    x <- dt 
    x <- reduce(x, full_join, by = 'id_prof')  
    return(x)
  }
```

**Comment by angelini75** [comment]
Un warning también vendría bien para los casos como el de tu ejemplo
