### ISSUE TITLE
autorización para descargar datos de los perfiles

### ISSUE THREAD

**Issue by leotenti** [INTA-Suelos/SISINTAR#19]
¿Me podrían autorizar?

``` perfiles <- get_perfiles(c(3182, 4609))
Warning message:
In get_perfiles(c(3182, 4609)) :
  No se pudieron descargar los siguientes perfiles:
  * 4609 (#2). Razón: No estás autorizado para realizar esta acción ```

**Comment by angelini75** [comment]
No, esto quiere decir que ese perfil no es público, por eso te arroja ese error. @paocorrales Siría posible autenticarse para que te lo deje descargar? Me imagino que eso implica un gran desarrollo

**Comment by paocorrales** [comment]
Hola! Tendríamos que mirarlo, podriamos Elio y/o yo tener usuario para autenticarnos y hacer alguna prueba?

**Comment by angelini75** [comment]
Si, registrate y te doy derechos de admin

**Comment by paocorrales** [comment]
Listo, me registré con mi mail.

**Comment by angelini75** [comment]
ya tenes acceso de admin

**Comment by eliocamp** [comment]
La última versión agrega la posibilidad de pasar un usuario y contraseña. Esto debería funcionar:

```r
get_perfiles(4609, credenciales = list(usuario = "usuario",
                                       pass = "pass"))
```

**Comment by leotenti** [comment]
Hola Elio. En mi caso sigo sin poder descargar perfiles con credenciales. Esto es útil para descargar toda la base. Para descargar ciertos perfiles
```datos <- get_perfiles(c(6653, 6347, 6580))``` 
funciona bien sin credenciales.

Cuando es necesario descargar toda la base con el siguiente código (también con algún perfil o selección):
```a <- buscar_perfiles()
get_perfiles(a, 
             dir = "Documents/GDB/SUELOS/", 
             credenciales = list(usuario = "tentivuegen.leonardo@inta.gob.ar",
                                 pass = "sisintatenti"))```
tira primero:
> a <- buscar_perfiles()
Descargando información de perfiles...
probando la URL 'http://sisinta.inta.gob.ar/es/perfiles.geojson'
Content type 'application/json; charset=utf-8' length unknown
downloaded 1.8 MB
Error in unlink(x) : file name conversion problem -- name too long?

y después:
> get_perfiles(a, 
+              dir = "Documents/GDB/SUELOS/", 
+              credenciales = list(usuario = "tentivuegen.leonardo@inta.gob.ar",
+                                  pass = "sisintatenti"))
Error in get_perfiles(a, dir = "Documents/GDB/SUELOS/", credenciales = list(usuario = "tentivuegen.leonardo@inta.gob.ar",  : 
  unused argument (credenciales = list(usuario = "tentivuegen.leonardo@inta.gob.ar", pass = "sisintatenti"))

**Comment by eliocamp** [comment]
¿Estás usando la última versión? Por el último error, parecería que tu versión del paquete no está aceptando el argumento "creenciales".

**Comment by dariorodriguez** [comment]
Para cerrar esto tendríamos que estar seguros que SOLO los administradores puedan tener acceso a los perfiles privados. Una posibilidad que nos da Sisinta es usarla para ir cargando perfiles como un repositorio a los cuales sólo tiene acceso el autor y a lo sumo los administradores. Imaginemos un tesista que carga los datos que va obteniendo del campo. Si eso alguien lo puede usar antes que la persona publique su tesis y libere los datos podemos tener un gran problema.
