### ISSUE TITLE
Interpolación de variables categóricas

### ISSUE THREAD

**Issue by eliocamp** [INTA-Suelos/SISINTAR#22]
En principio la interpolación (ya sea con promedio ponderado o con splines) sólo tiene sentido para variables continuas. ¿Qué pasa si el usuario quiere un perfil en horizontes estandarizados que además contenga variables categóricas? @angelini75

**Comment by angelini75** [comment]
La realidad es que nadie pediría un spline de variables categóricas. Quizás se debería exporta variables categóricas en un csv y continuas en otro csv, por default. De esa manera no habría conflictos.
De exportarse juntas, si el spline es de 0-100cm, las variables categóricas podrían contener las clases como tags en un solo campo, en orden de importancia (espesor). 
Pero quizás para esto se puede hacer una función específica que convierta variables categóricas en dos campos, de tal manera que quede
```
id_hor=id del horizonte
clase=la clase de la variable, 
importancia=el espesor de esa clase en un rango determinado (0-100, por ejemplo)
```

**Comment by eliocamp** [comment]
Separar con "|".
