### ISSUE TITLE
Error - comunicacion x web de INTA

### ISSUE THREAD

**Issue by yabellini** [INTA-Suelos/SISINTAR#32]
Buenas tardes Dra Saibene,
Quise instalar el paquete SISINTAR en R y me da error con el siguiente mensaje : " cannot open URL 'http://sisinta.inta.gob.ar/es/perfiles.geojson': HTTP status was '503 Service Temporarily Unavailable "
Error: Failed to install 'SISINTAR' from GitHub:
System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 34-36 (ejemplos-de-uso.Rmd)
E> Error: processing vignette 'ejemplos-de-uso.Rmd' failed with diagnostics:
E> cannot open URL 'http://sisinta.inta.gob.ar/es/perfiles.geojson'
E> --- failed re-building 'ejemplos-de-uso.Rmd'
E>
E> SUMMARY: processing the following file failed:
E> 'ejemplos-de-uso.Rmd'
E>
E> Error: Vignette re-building failed.
E> Execution halted

**Comment by eliocamp** [comment]
Claro, no anda la web y entonces no anda el paquete. 

Esa URL es necesaria para tener el listado actualizado de los perfiles disponibles. Se me ocurre que podríamos hostear el archivo acá en github y armar un github actions que cada X días lo actualice.

**Comment by eliocamp** [comment]
Quizás habría que hacer lo mismo con los datos en sí ya que por más que baje ese archivo, después va a fallar la descarga. El tema es que eso tarda mucho en bajar, por lo que puede fallar.

**Comment by eliocamp** [comment]
La otra es pedirles si se puede hacer un cron **en el servidor** que suba los archivos al github automáticamente cuando cambien. ¿Será factible eso?

**Comment by yabellini** [comment]
Mirá este nuevo error Elio:
Buenos dias Yanina ,
Quise utilizar el paquete SisIntaR nuevamente, pero me da error (copiado mas abajo). Entiendo que deberia existir un archivo en "[https://raw.githubusercontent.com/INTA-Suelos/SISINTAR/main/data-raw/per...](https://raw.githubusercontent.com/INTA-Suelos/SISINTAR/main/data-raw/perfiles.geojson) pero que tal archivo no existe? Agradeceria me indique como debo proceder para poder finalmente hacer uso del paquete SISINTAR y acceder a los datos de suelo.
Cordiales saludos!
Eugenia
library(SISINTAR)
library(dplyr)
buscar_perfiles()
Descargando información de perfiles...
Error in utils::download.file("[https://raw.githubusercontent.com/INTA-Suelos/SISINTAR/main/data-raw/per...](https://raw.githubusercontent.com/INTA-Suelos/SISINTAR/main/data-raw/perfiles.geojson), :
cannot open URL '[https://raw.githubusercontent.com/INTA-Suelos/SISINTAR/main/data-raw/per...](https://raw.githubusercontent.com/INTA-Suelos/SISINTAR/main/data-raw/perfiles.geojson')
In addition: Warning message:
In utils::download.file("[https://raw.githubusercontent.com/INTA-Suelos/SISINTAR/main/data-raw/per...](https://raw.githubusercontent.com/INTA-Suelos/SISINTAR/main/data-raw/perfiles.geojson), :
cannot open URL '[https://raw.githubusercontent.com/INTA-Suelos/SISINTAR/main/data-raw/per...](https://raw.githubusercontent.com/INTA-Suelos/SISINTAR/main/data-raw/perfiles.geojson':) HTTP status was '404 Not Found'

**Comment by yabellini** [comment]
EL servidor ayer estaba funcionando.

**Comment by eliocamp** [comment]
Es el mismo error. Cambié el código para que busque el archivo acá en github pero todavía no pude encontrar el servidor andando como para transferirlo acá. 

> EL servidor ayer estaba funcionando.
Probé un par de veces y nunga lo ví andar. Ahora está caido :sob:

**Comment by eliocamp** [comment]
Ok, ahora funciona. Bajé la base en otro repositorio: https://github.com/INTA-Suelos/sisintar-datos

El repo tiene un script para bajar los datos. Lo probé y anduvo (bajó la base en ~8minutos) pero no al 100% ya que algunos archivos se bajaron vacíos y no sé por qué. 

Además, me di cuenta que esto sólo lo podemos hacer para los datos públicos. :\

En resumen: me gusta poco esta solución. Creo que lo que hay que hacer es asegurarnos de:

1. que el paquete se pueda instalar sin depender de que funcione SISINTA. Para eso hay que evitar bajar datos del servidor en las viñetas. 
2. chequear y tirar un error informativo si la SISINTA está caído.

**Comment by eliocamp** [comment]
Listo. Ahora sólo queda esperar que se caiga SISINTAR e intentar instalar el paquete :P

**Comment by yabellini** [comment]
> 

Estoy de acuerdo con los dos puntos. Que no dependa de sistinta y que avise que está caido si es que lo intentan usar.

**Comment by eliocamp** [comment]
Perfecto. Creo que ya estaría andando :+1:

**Comment by yabellini** [comment]
Le sigue dando error:

![imagen](https://user-images.githubusercontent.com/2473676/159009665-65c2992d-abbb-4b17-8668-2fc8ea860e57.png)

**Comment by yabellini** [comment]
Este es el error que le da cuando intenta instalar el paquete de nuevo para tener la última versión.  Falla de nuevo en las vignetas:

![imagen](https://user-images.githubusercontent.com/2473676/159138507-0aa1e301-35a6-4792-a400-886525ed61d3.png)

**Comment by eliocamp** [comment]
No lo puedo reproducir en mi lado. Por el mensaje de error (`argument 'txt' must be a JSON string, URL or file`) parecería que es un problema al descargar el .geojson... otra vez. Que se descargó pero no con formato json? 
Estoy instalando y no tengo problema. 

Una cosa que voy a hacer es cambiar las instrucciones de instalación para que no corra la viñeta, que nos da muchos problemas.

**Comment by yabellini** [comment]
Si me pasa lo mismo. Yo lo instale en dos maquinas diferentes sin problemas. 

Igual creó un issue (a pedido mio) y recién lo cerró porque pudo hacerlo funcionar. Ahora linkeo a lo que hizo.
