### ISSUE TITLE
Error al instalar SISINTAR desde github

### ISSUE THREAD

**Issue by emunaro** [INTA-Suelos/SISINTAR#33]
El transcript de console de Rstudio
> **sessionInfo()**
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0    curl_4.3.2     remotes_2.4.2 

Al correr 
```

<remotes::install_github("INTA-Suelos/SISINTAR", build_vignettes = TRUE, force=TRUE)
```

Obtengo el siguiente error: 

Downloading GitHub repo INTA-Suelos/SISINTAR@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: Rcpp (1.0.8 -> 1.0.8.3) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
Running `R CMD build`...
* checking for file 'C:\Users\EugeniaMunaro\AppData\Local\Temp\RtmpeSDj2J\remotes3d8168a115d\INTA-Suelos-SISINTAR-1246e55/DESCRIPTION' ... OK
* preparing 'SISINTAR':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building 'ejemplos-de-uso.Rmd' using rmarkdown
Error: processing vignette 'ejemplos-de-uso.Rmd' failed with diagnostics:
there is no package called 'rmarkdown'
--- failed re-building 'ejemplos-de-uso.Rmd'

SUMMARY: processing the following file failed:
  'ejemplos-de-uso.Rmd'

Error: Vignette re-building failed.
Execution halted
STDOUT:
* checking for file 'C:\Users\EugeniaMunaro\AppData\Local\Temp\RtmpeSDj2J\remotes3d8168a115d\INTA-Suelos-SISINTAR-1246e55/DESCRIPTION' ... OK
* preparing 'SISINTAR':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building 'ejemplos-de-uso.Rmd' using rmarkdown
Error: processing vignette 'ejemplos-de-uso.Rmd' failed with diagnostics:
there is no package called 'rmarkdown'
--- failed re-building 'ejemplos-de-uso.Rmd'

SUMMARY: processing the following file failed:
  'ejemplos-de-uso.Rmd'

Error: Vignette re-building failed.
Execution halted
STDERR:

Error: Failed to install 'SISINTAR' from GitHub:
  Failed to `R CMD build` package, try `build = FALSE`.

**Comment by emunaro** [comment]
Agregue `build = FALSE` to remote::install_github y se soluciono el  error.

**Comment by yabellini** [comment]
Genial!

**Comment by eliocamp** [comment]
No tenés instalado el paquete rmarkdown, que es necesario para renderizar la viñeta. Con esto se debería instalar:

```r
remotes::install_github("INTA-Suelos/SISINTAR", build_vignettes = TRUE, force=TRUE, depencencies = TRUE)
```
