### ISSUE TITLE
Descarga y lectura programática de datos desde SiSINTA

### ISSUE THREAD

**Issue by yabellini** [INTA-Suelos/SISINTAR#4]

**Comment by eliocamp** [comment]
Cosas para hacer:

* [x] Descargue los datos de sisinta
* [x] Devuelva un dataframe
* [ ] Le ponga nombres razonables a las columnas   
   * [ ] sacarle el prefijo "perfil_" a las variables del perfil 
   * [ ] sacarla el prefijo "analitico_" a las variables de analítico. 
* [ ] Elimine las columnas redundantes? ("analitico_profundidad_muestra" es al pedo porque están las columnas "profundidad_inferior" y "profundidad_superior")
* [ ] Lidiar con datos faltantes en las profundidades

Otras utilidades:
* [ ] Búsqueda 
   * [ ] Por provincia
   * [ ] Por lon lat
   * [ ] Por rango de fecha?
   * [ ] Por serie?

**Comment by paocorrales** [comment]
Las funciones `get_perfiles()` y `as_SoilProfileColection()` están en beta y esperan ser probadas. La documentación es preliminar pero incluye un ejemplo para correr rápido.

```
perfiles <- get_perfiles(c(3238, 4634))
coleccion <- as_SoilProfileCollection(perfiles)
```

**Comment by angelini75** [comment]
Para los nombres razonables necesitarias un documento tipo diccionario?

**Comment by eliocamp** [comment]
Sí. 
Lo ideal creo que sería tener dos cosas. Una, una lista para renombrar las columnas si es necesario, y un diccionario de datos con documentación de qué es cada columna para que esté en el paquete y lo use el usuario.

**Comment by angelini75** [comment]
Tenemos una tabla bastante avanzada:
https://docs.google.com/spreadsheets/d/1cLS1jBjXUzfWOH-I7LbzSDJJiQuv9usOaDUdpBuyZBc/edit?usp=sharing

@dariorodriguez @leotenti podríamos terminar esta tabla?

**Comment by eliocamp** [comment]
Estoy mirando el tema de exportar a shapefile y este formato tiene la limitación de que las columnas no pueden tener más de 10 caracteres. Si exportar a shapefile es prioridad, habría que tener en cuenta eso para el nombre estandarizado de las variables en R.

**Comment by angelini75** [comment]
No es de alta prioridad, si a MS Excel
