### ISSUE TITLE
Funciones de Filtrado y selección de observaciones y variables

### ISSUE THREAD

**Issue by yabellini** [INTA-Suelos/SISINTAR#5]
* Obtener nombre de variales
- [ ]  get_variable_sitio()
- [ ]  get_variable_horizonte()
* Selección de variables
- [ ]  selección de variables de sitio, y/o
- [ ]  selección de variables de horizontes
* Filtrar
- [ ] filtrar perfiles por variables de sitio (por ejemplo, por ubicación o radio definido por el usuario)
- [ ] filtrar perfiles por variables de horizontes (por ejemplo, por contenido de materia orgánica)
- [ ] filtrar horizontes de acuerdo a ciertas variables de horizontes (por ejemplo, nombre que contenga “A”)
* Devolver información sintetizada:
- [ ] generar horizontes estandarizados a partir de horizontes originales. Por ejemplo, generar una tabla que contenga Latitud, Longitud, Materia_Oránica_0-30cm (limite superior = 0, limite inferior = 30).
- [ ] utilizar diferentes métodos de sintetizado: función spline o promedio ponderado, o valor para una profundidad única (ej. 5 cm)
* Función contar:
- [ ] contar horizontes por perfil (con/sin NAs en una variable)
- [ ] contar número de perfiles en un dataset (con/sin NAs en una variable)

**Comment by eliocamp** [comment]
Preugnta: ¿La idea es que dentro del paquete se trabaje siempre con objetos de clase SoilProfileCollection o con data.frames? Si es lo primero, entonces varias de estas funciones implicarían implementar verbos de dplyr para esta clase. Me fijé y hay los devs [están hablando de eso](https://github.com/ncss-tech/aqp/issues/118) y podríamos tomarlo y acelerarlo nosotres.

**Comment by angelini75** [comment]
No lo tengo claro, creo que si se pudieran hacer ambas cosas mejor. de tener que elegir solo una, me parece que habría que ir por data.frames.
