### ISSUE TITLE
Funciones de Exportación de datos

### ISSUE THREAD

**Issue by yabellini** [INTA-Suelos/SISINTAR#6]
Posibilidad de exportación a MS Excel y/o ESRI shape file. Archivos Excel deberían separar una tabla para datos de sitio y otra para datos de horizontes.

**Comment by eliocamp** [comment]
Para exportar a shapefile hay que resolver el tema de los nombres de columnas, porque con nombres "largos" (más de 10 caracteres) [explota todo](https://github.com/INTA-Suelos/SISINTAR/issues/4#issuecomment-841878364).

**Comment by paocorrales** [comment]
Queda para el futuro exportar a shape file, si deciden nombres de variables cortos.
