### ISSUE TITLE
Qué hacer si alguna profundidad es NA

### ISSUE THREAD

**Issue by eliocamp** [INTA-Suelos/SISINTAR#8]
Para el perfil 3238, la profundidad_inferior el último horizonte es un dato faltante. Al transformar en un SoilProfileCollection, aqp se queja. ¿Qué hacemos con eso?

**Comment by dariorodriguez** [comment]
Hola Elio, eso puede pasar en bastantes perfiles. La base la estamos curando y poco a poco deberían dejar de aparecer esos valores. En principio si es una capa restrictiva para las raíces (Tosca, Duripán, etc.) completamos con 5 cm más. Ej: IICcam 120+ ponemos IICcam 120-125

**Comment by dariorodriguez** [comment]
Ya que consideramos que el que hizo el pozo llegó hasta ahí y no pudo cavar más que unos pocos cm

**Comment by paocorrales** [comment]
Gracias! Podemos incluir ese control de calidad al descargar un perfil, podrías indicarnos cuales son todas las capas donde el criterio que mencionaste es válido? En que variable de la base de datos encontramos el tipo de capa?

**Comment by dariorodriguez** [comment]
Es válido sólo en el último horizonte o capa.

**Comment by dariorodriguez** [comment]
Sería Clase Hz

**Comment by angelini75** [comment]
@paocorrales, la variable es 'horizonte'
@eliocamp si el horizonte no es el ultimo (el más profundo) del perfil, debería sacarlo y un warning debería decir el perfil_id = 111 se excluyó del analisis por contener NA en un horizonte
Si el NA está en el limite inferior de la última capa, agregaría un argumento del tipo fix = TRUE/FALSE para que en vez de eliminarlo le reemplace ese NA por profundidad_superior + un valor dado por el usuario.
Por último, habría que dejar claro que un NA en una profundidad que no es la última, es un problema de carga de datos, mientras que el otro es intrínseco a los datos.

**Comment by eliocamp** [comment]
¿Eso tendría que estar en alguna función tipo "validar_perfiles()" como la que está [acá](https://github.com/DiazSergio/VariabilidadCOS/blob/master/codigosR/01_validarCrearSPC.R)?

**Comment by angelini75** [comment]
Claro, sería ideal.
